version: '3.8'

services:
  obu-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obu-frontend-app
    # ports:
    #   - "3031:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - obu-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8444:8444"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - obu-network
    depends_on:
      - obu-frontend
    restart: unless-stopped

networks:
  obu-network:
    driver: bridge

volumes:
  caddy_data:
