version: '3.8'

services:
  obu-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obu-frontend-app
    # ports:
    #   - "3031:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - obu-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - obu-network
    depends_on:
      - obu-frontend
    restart: unless-stopped

networks:
  obu-network:
    driver: bridge
